// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAJO12vUt-1vG3LpJJvBVbXr7jhOayEVU',
    appId: '1:161437126606:web:f0b516d84ce7d5fbd9659f',
    messagingSenderId: '161437126606',
    projectId: 'rtvd-test',
    authDomain: 'rtvd-test.firebaseapp.com',
    storageBucket: 'rtvd-test.appspot.com',
    measurementId: 'G-TLZELR12BW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg3ZyMX3dZn4qmM4XepgAcQTFkiq4LRag',
    appId: '1:161437126606:android:84e19a3d731a70ced9659f',
    messagingSenderId: '161437126606',
    projectId: 'rtvd-test',
    storageBucket: 'rtvd-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAvITDf6vDvT1SGgmfUhWmsWsMV7z2fuA',
    appId: '1:161437126606:ios:677cb8911bad29add9659f',
    messagingSenderId: '161437126606',
    projectId: 'rtvd-test',
    storageBucket: 'rtvd-test.appspot.com',
    iosClientId: '161437126606-u8makvqdj9an0tsrtjj9a4nuivd2mr3v.apps.googleusercontent.com',
    iosBundleId: 'com.nerdalert.rtvd-admin',
  );
}
