-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgunLEfRZhtboikuK3
U8J46PydGVwHEngTIsZUUEzDcZqgCgYIKoZIzj0DAQehRANCAATRDZCZ6xMjCXmG
lYPjLkm80hvMD9l6wJXto99E4pHNS5iUQcvyUSV2YMzBORsd4RhejByyve5TznU7
8wNdoT4h
-----END PRIVATE KEY-----